#Allure environment
#Fri May 22 12:05:42 IST 2026
AddOffering\ URL=https\://st.dbss-rm.oci-np.kpn.org/bcws/webresources/v1.0/custom/changeOffering
ChangeServiceAttribute\ URL=https\://st.dbss-rm.oci-np.kpn.org/bcws/webresources/v1.0/custom/changeServiceAttribute
Database=Oracle (ojdbc8)
Environment=ST
SIM\ preactivation\ Base\ URL=http\://localhost\:1119
Topup\ URL=https\://st.dbss-rm.oci-np.kpn.org/brm/extn/prepayBalanceManagement/v4/topupBalance
